services:
  powerdns:
    image: powerdns/pdns-auth-50:latest
    environment:
      PDNS_AUTH_API_KEY: secret
    ports:
      - 8081:8081
      - 8053:53/udp
      - 8053:53/tcp
    volumes:
      - ./docker/pdns.conf:/etc/powerdns/pdns.conf:ro